### ISSUE TITLE
iOS 错误

### ISSUE THREAD

**Issue by lovachen** [leanflutter/flutter_qiyu#12]
[!] CocoaPods could not find compatible versions for pod "flutter_qiyu":
  In Podfile:
    flutter_qiyu (from `.symlinks/plugins/flutter_qiyu/ios`)

Specs satisfying the `flutter_qiyu (from `.symlinks/plugins/flutter_qiyu/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by lijy91** [comment]
需要将 deployment target 修改为 10.0 

https://github.com/leanflutter/flutter_qiyu/blob/main/example/ios/Podfile
