### ISSUE TITLE
求大神更新版本或联系交流沟通

### ISSUE THREAD

**Issue by JianningRuan** [leanflutter/flutter_qiyu#15]
现在七鱼更新了9.1.0了，然后ios17发现现在旧版的发送不了图片，想您更新一版或者请教你怎么去改一版

**Comment by lijy91** [comment]
微信 lijy91

**Comment by JianningRuan** [comment]
更新到qiyu1.0.2版本之后，ios端只能通过iPhone真机连接mac去调试了，原因暂未明，七鱼工程师也没有给出答复

**Comment by JianningRuan** [comment]
更新到qiyu0.1.2版本之后，ios端只能通过iPhone真机连接mac去调试了，原因暂未明，七鱼工程师也没有给出答复
