### ISSUE TITLE
请教下MainActivity.kt中怎么初始化

### ISSUE THREAD

**Issue by slimcheng** [leanflutter/flutter_qiyu#3]
项目创建时候使用的是默认的kotlin，请教下在MainActivity.kt中怎么进行初始化

**Comment by lijy91** [comment]
如果是Kotlin 的话需要你自己创建一个 MainApplication.kt 文件，将初始化的代码添加到 MainApplication.kt

**Comment by slimcheng** [comment]
最后还是把kotlin改成java的了，安卓下没问题了！
