### ISSUE TITLE
程序包com.netease.nimlib.sdk不存在

### ISSUE THREAD

**Issue by kyle215** [leanflutter/flutter_qiyu#4]
flutter 添加您的插件后是这个错误。

如下修改，错误解决，应该是版本更新引起的：
//import com.netease.nimlib.sdk.RequestCallback;
//import com.netease.nimlib.sdk.StatusBarNotificationConfig;

import com.qiyukf.nimlib.sdk.RequestCallback;
import com.qiyukf.nimlib.sdk.StatusBarNotificationConfig;

**Comment by lijy91** [comment]
请更新到 `0.0.2`
