### ISSUE TITLE
iOS build 时错误

### ISSUE THREAD

**Issue by kyle215** [leanflutter/flutter_qiyu#5]
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_QYUserInfo", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYCommodityInfo", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSource", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
      "_OBJC_CLASS_$_QYSDK", referenced from:
          objc-class-ref in libflutter_qiyu.a(FlutterQiyuPlugin.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system

**Comment by lijy91** [comment]
请参考一下下面两个 Issue
https://github.com/leanflutter/flutter_qiyu/issues/1
https://github.com/leanflutter/flutter_qiyu/issues/2
